apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-nginx-generator
data:
  nginx-generator-literal1: "value-from-dev $(NAMESPACE)"
  nginx-generator-from-file2: |-
    This is a common text 2 (nginx-dev) $(NAMESPACE)
