apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-nginx-resource
data:
  nginx-resource-literal1: "value-from-dev $(NAMESPACE)"
  nginx-resource-text1: |-
    This is a common text (nginx-dev) $(NAMESPACE)
