bases:
- ../base
namespace: dev-nginx-test
namePrefix: dev-
commonLabels:
  stage: dev
commonAnnotations:
  com.trilogy.stage: dev
patches:
- cm-nginx-resource.yml
patchesStrategicMerge:
- sts-nginx.yml
- cm-nginx-generator.yml
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ing-nginx
  path: ing-patch.yml
