bases:
- ../base
patches:
- ss-nginx.yml
- cm-nginx-resource.yml
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ing-nginx
  path: ingress-patch.yml
namespace: prod-nginx-test
namePrefix: prod-
commonLabels:
  stage: prod
commonAnnotations:
  com.trilogy.stage: prod
patchesStrategicMerge:
- cm-nginx-generator.yml
